# Generated by Django 4.2.6 on 2023-11-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_nurse_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(max_length=250)),
                ('diet_restrictions', models.CharField(max_length=250)),
                ('Test_conducted', models.CharField(max_length=250)),
                ('prescriptions', models.CharField(max_length=250)),
                ('Drug_history', models.CharField(max_length=250)),
                ('Family_history', models.CharField(max_length=250)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
