# Generated by Django 4.2.6 on 2023-11-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_ehr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ehr',
            old_name='diet_restrictions',
            new_name='diet_restriction',
        ),
    ]
