# Generated by Django 4.2.6 on 2023-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_diet_restrictions_ehr_diet_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Doctor',
            field=models.ManyToManyField(blank=True, to='hospital.doctor'),
        ),
    ]
