# Generated by Django 4.2.6 on 2023-11-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=350)),
                ('Email', models.EmailField(max_length=254)),
                ('person_type', models.CharField(max_length=50)),
            ],
        ),
    ]
