# Generated by Django 4.2.6 on 2023-12-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_message_receiver_message_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.nurse'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.doctor'),
        ),
    ]
