# Generated by Django 4.2.6 on 2023-12-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_message_nurse_nurse_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Ehr_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.patient')),
            ],
        ),
    ]
